# Basic Information
title: 查超 | Zha Chao
position: Ph.D. Candidate
affiliation: Institute of Computing Technology, Chinese Academy of Sciences
affiliation_link: https://www.ict.ac.cn/
email: zhachao21(at)mails.ucas.ac.cn
birth: 1995.07

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: 查超, Zha Chao, AI for Security, Network Intrusion Detection System, Network Traffic Classification, Network Traffic Analysis
description: Zha Chao's academic homepage. Research interests include AI for Security, Network Intrusion Detection System, Network Traffic Classification, Network Traffic Analysis.
canonical: 

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=iZ-cDDkAAAAJ&hl=zh-CN&oi=sra
cv_link: ./resume.pdf
github_link: https://github.com/ids-sec-hub
wechat: 
linkedin:
twitter:

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./Me.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Sans Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics:

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
